# Generated by Django 3.0.8 on 2021-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('멘티', '멘티'), ('멘토', '멘토')], default='멘티', max_length=5, verbose_name='역할'),
        ),
    ]
