# Generated by Django 3.0.8 on 2020-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sold_out',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
    ]
