# Generated by Django 3.0.8 on 2021-02-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='인증 일시'),
        ),
    ]
