# Generated by Django 3.0.8 on 2020-11-26 01:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_soldout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(validators=[api.models.rate_validator], verbose_name='평점'),
        ),
    ]
