# Generated by Django 3.0.8 on 2021-01-03 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('contact', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=5, verbose_name='성별')),
                ('region', models.CharField(max_length=20, verbose_name='지역')),
                ('introduction', models.CharField(max_length=40, verbose_name='한줄 소개')),
                ('career', models.CharField(max_length=100, verbose_name='경력')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='tenant',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='review',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Mentor', verbose_name='멘토'),
        ),
    ]
