# Generated by Django 3.0.8 on 2021-02-24 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_smsauth_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='예약 날짜')),
                ('complete', models.BooleanField(default=False, verbose_name='예약 완료 여부')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='api.Room', verbose_name='매물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
            ],
        ),
    ]
