# Generated by Django 3.0.8 on 2020-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201126_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='우편번호'),
        ),
    ]
