# Generated by Django 3.0.8 on 2021-01-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210103_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=40, verbose_name='한줄 평'),
        ),
    ]
