# Generated by Django 3.0.8 on 2021-01-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210107_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='address_detail',
            field=models.CharField(default='sadf', max_length=50, verbose_name='상세주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=50, verbose_name='주소'),
        ),
    ]
